Fix build for bullseye; 1.4.3-0osso3

diff --git a/Dockerfile.build b/Dockerfile.build
--- a/Dockerfile.build
+++ b/Dockerfile.build
@@ -1,9 +1,9 @@
-#!/bin/bash
+#!/bin/sh
 cd "$(dirname "$0")"  # jump to curdir
+set -eu
 
 # Pass these on the command line.
-oscodename=${1:-debian/stretch}  # debian/stretch
-
+oscodename=${1:-debian/bullseye}  # debian/stretch
 buildversion=$(sed -e '1!d;s/.*(//;s/).*//' changelog)
 upname=asterisk-g72x
 upversion=$(echo "$buildversion" | sed -e 's/-.*//;s/^[0-9]*://')
@@ -17,22 +17,20 @@ echo ".. continuing"
 
 osdistro=${oscodename%/*}   # debian (or ubuntu)
 oscodename=${oscodename#*/} # stretch (or bionic)
-osdistshort=${osdistro:0:3} # deb (or ubu)
 case $osdistro/$oscodename in
-debian/buster)  oscodenum=10;;
-debian/stretch) oscodenum=9;;
-debian/jessie)  oscodenum=8;;
-debian/wheezy)  oscodenum=7;;
-ubuntu/bionic)  oscodenum=18.04;;
-ubuntu/xenial)  oscodenum=16.04;;
-ubuntu/trusty)  oscodenum=14.04;;
+debian/bullseye)osdistshort=deb; oscodenum=11;;
+debian/buster)  osdistshort=deb; oscodenum=10;;
+debian/stretch) osdistshort=deb; oscodenum=9;;
+debian/jessie)  osdistshort=deb; oscodenum=8;;
+debian/wheezy)  osdistshort=deb; oscodenum=7;;
+ubuntu/jammy)   osdistshort=ubu; oscodenum=22.04;;
+ubuntu/focal)   osdistshort=ubu; oscodenum=20.04;;
+ubuntu/bionic)  osdistshort=ubu; oscodenum=18.04;;
+ubuntu/xenial)  osdistshort=ubu; oscodenum=16.04;;
+ubuntu/trusty)  osdistshort=ubu; oscodenum=14.04;;
 *) echo "ERROR: undefined OS: $osdistro/$oscodename" >&2 && exit 1
 esac
 _shortver=$osdistshort$oscodenum
-
-# Update changelog
-sed -i -e "1s/+\\(deb\\|ubu\\)[0-9.]*) [a-z]\\+;/+$_shortver) $oscodename;/" \
-    changelog
 
 # Docker disallows certain tokens in versions.
 dockversion=$(echo build-${upname}-${upversion}-${debversion}-${oscodename} |
@@ -51,10 +49,9 @@ docker build \
     --build-arg debversion=$debversion \
     -t $dockversion \
     -f Dockerfile \
-    .
-ret=$?
-if test $ret -ne 0; then
-    echo "fail ($ret)" >&2
+    . || ret=$?
+if test ${ret:-0} -ne 0; then
+    echo "fail" >&2
     exit $ret
 fi
 
